# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Check lockfile
        run: |
          if [ ! -f package-lock.json ]; then echo "Missing package-lock.json" && exit 1; fi
          if [ ! -f yarn.lock ]; then echo "Missing yarn.lock" && exit 1; fi
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
